### ISSUE TITLE
test

### ISSUE THREAD

**Issue by jatinchauhan20** [jatinchauhan20/flutter-project#1]
testing issue for physical device
`Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\Users\JATIN\StudioProjects\first_project\build\app\outputs\flutter-apk\app-debug.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
Error launching application on M2003J15SC.
`

**Comment by imtusharrai** [comment]
Your Emulator is running out of space, clear its cache:

Click on AVD Manager
Wipe Data (Your Target Device )
![fQ3O4](https://github.com/user-attachments/assets/63f91dd8-b17c-4a09-aea1-d1bbebbd0bed)
You are set to go.
